# Generated by Django 3.1.4 on 2022-04-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220418_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
