# Generated by Django 3.1.4 on 2022-04-19 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220418_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
