# Generated by Django 4.0.4 on 2022-05-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plan_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSV_STORE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='media/')),
            ],
        ),
    ]
